# Generated by Django 6.1 on 2026-08-20 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='issues.reporter'),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='team',
            field=models.CharField(max_length=100),
        ),
    ]
